### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by ninjamask** [python-oursql/oursql#13]
```
C:\pwb>pip install -r requirements.txt
Requirement already satisfied: httplib2>=0.9.0 in c:\users\ninjamask\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line
 22))
Requirement already satisfied: pydot in c:\users\ninjamask\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 25))
Requirement already satisfied: google>=1.7 in c:\users\ninjamask\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 28))
Requirement already satisfied: crontab in c:\users\ninjamask\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 31))
Requirement already satisfied: argparse in c:\users\ninjamask\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 34))
Requirement already satisfied: Pillow in c:\users\ninjamask\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 43))
Requirement already satisfied: flickrapi in c:\users\ninjamask\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 44))
Requirement already satisfied: irc in c:\users\ninjamask\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 47))
Requirement already satisfied: mwparserfromhell>=0.3.3 in c:\users\ninjamask\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 50))
Collecting oursql (from -r requirements.txt (line 54))
  Using cached oursql-0.9.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Windows\TEMP\pip-build-lp62r574\oursql\setup.py", line 53
        print "cython not found, using previously-cython'd .c file."
                                                                   ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Windows\TEMP\pip-build-lp62r574\oursql\
```

**Comment by ninjamask** [comment]
```
C:\pwb>pip install oursql
Collecting oursql
  Using cached oursql-0.9.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Windows\TEMP\pip-build-c83f8lvj\oursql\setup.py", line 53
        print "cython not found, using previously-cython'd .c file."
                                                                   ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Windows\TEMP\pip-build-c83f8lvj\oursql\
```

**Comment by phdru** [comment]
I fixed that in #8.

**Comment by phdru** [comment]
To install for Python 3 use branch py3k. I forked oursql and applied missing PRs, see the results at https://github.com/sqlobject/oursql
